In [1]:
from IPython.display import HTML
HTML("""
<style>

/* 1️⃣ 让整体容器铺满 */
.container {
    width: 100% !important;
    max-width: 100% !important;
}

/* 2️⃣ 代码输入区自动换行 */
div.input_area pre {
    white-space: pre-wrap !important;
    word-break: break-word !important;
}

/* 3️⃣ 代码高亮区域也处理 */
div.highlight pre {
    white-space: pre-wrap !important;
    word-break: break-word !important;
}

/* 4️⃣ 防止代码块横向撑破 */
div.input_area {
    overflow-x: auto;
}

/* 5️⃣ 表格横向滚动 */
table {
    display: block;
    overflow-x: auto;
}

</style>
""")

In [1]:
import torch
import numpy as np
torch.__version__

'2.7.1'

### 创建张量

In [2]:
#张量——标量
torch.tensor([1],dtype=torch.float32)

tensor([1.])

In [3]:
#张量——向量
torch.arange(5,dtype=torch.float32)

tensor([0., 1., 2., 3., 4.])

In [4]:
#张量——矩阵
torch.arange(6,dtype=torch.float32).reshape(2,3)

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
#张量——三维
torch.arange(8,dtype=torch.float32).reshape(2,2,2)

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [6]:
#张量——四维
torch.arange(24,dtype=torch.float32).reshape(2,2,2,3)

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],

         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]],


        [[[12., 13., 14.],
          [15., 16., 17.]],

         [[18., 19., 20.],
          [21., 22., 23.]]]])

### 查看张量

In [7]:
x = torch.arange(8,dtype=torch.float32).reshape(2,2,2)

In [8]:
#查看张量形状
x.size()

torch.Size([2, 2, 2])

In [9]:
#查看张量形状
x.shape

torch.Size([2, 2, 2])

In [10]:
#查看张量中元素总数
x.numel()

8

In [11]:
#查看张量维度
x.ndim

3

In [12]:
#枚举张量每一个元素
for a in range(x.shape[0]):
    for b in range(x.shape[1]):
        for c in range(x.shape[2]):
            print(f'张量索引位置[{a},{b},{c}]的元素是{x[a,b,c].item()}')

张量索引位置[0,0,0]的元素是0.0
张量索引位置[0,0,1]的元素是1.0
张量索引位置[0,1,0]的元素是2.0
张量索引位置[0,1,1]的元素是3.0
张量索引位置[1,0,0]的元素是4.0
张量索引位置[1,0,1]的元素是5.0
张量索引位置[1,1,0]的元素是6.0
张量索引位置[1,1,1]的元素是7.0


### 张量升维与降维

In [13]:
x

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [14]:
#对第一维升维
torch.unsqueeze(x,dim=0)

tensor([[[[0., 1.],
          [2., 3.]],

         [[4., 5.],
          [6., 7.]]]])

In [15]:
#对第二维升维
torch.unsqueeze(x,dim=1)

tensor([[[[0., 1.],
          [2., 3.]]],


        [[[4., 5.],
          [6., 7.]]]])

In [16]:
#对第三维升维
torch.unsqueeze(x,dim=2)

tensor([[[[0., 1.]],

         [[2., 3.]]],


        [[[4., 5.]],

         [[6., 7.]]]])

In [17]:
torch.unsqueeze(x,dim=2).ndim

4

In [18]:
#对第一维降维
torch.squeeze(torch.unsqueeze(x,dim=0)).ndim

3

In [19]:
#只能对空维进行降维
torch.squeeze(x).ndim

3

In [20]:
#张量拉平至向量——方法一
x.flatten()

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [21]:
#张量拉平至向量——方法二
x.reshape(1,-1)

tensor([[0., 1., 2., 3., 4., 5., 6., 7.]])

In [22]:
#修改张量形状
display(x)
display(x.shape)
display(x.reshape(4,1,2))

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

torch.Size([2, 2, 2])

tensor([[[0., 1.]],

        [[2., 3.]],

        [[4., 5.]],

        [[6., 7.]]])

### 张量拼接与拆分

In [23]:
x

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [24]:
#垂直拼接
torch.stack([x for _ in range(2)],dim=0)

tensor([[[[0., 1.],
          [2., 3.]],

         [[4., 5.],
          [6., 7.]]],


        [[[0., 1.],
          [2., 3.]],

         [[4., 5.],
          [6., 7.]]]])

In [25]:
#水平拼接
torch.stack([x for _ in range(2)],dim=1)

tensor([[[[0., 1.],
          [2., 3.]],

         [[0., 1.],
          [2., 3.]]],


        [[[4., 5.],
          [6., 7.]],

         [[4., 5.],
          [6., 7.]]]])

In [26]:
x

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [27]:
#垂直拆分并降维
a,b = torch.split(x, split_size_or_sections=1, dim=0)
display(a,b)
display(a.squeeze(0), b.squeeze(0))

tensor([[[0., 1.],
         [2., 3.]]])

tensor([[[4., 5.],
         [6., 7.]]])

tensor([[0., 1.],
        [2., 3.]])

tensor([[4., 5.],
        [6., 7.]])

In [28]:
#水平拆分并降维
a,b = torch.split(x, split_size_or_sections=1, dim=1)
display(a,b)
display(a.squeeze(1), b.squeeze(1))

tensor([[[0., 1.]],

        [[4., 5.]]])

tensor([[[2., 3.]],

        [[6., 7.]]])

tensor([[0., 1.],
        [4., 5.]])

tensor([[2., 3.],
        [6., 7.]])

In [29]:
torch.cat((x,x),dim=0)

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]],

        [[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [30]:
torch.cat((x,x),dim=1)

tensor([[[0., 1.],
         [2., 3.],
         [0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.],
         [4., 5.],
         [6., 7.]]])

In [31]:
x

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [32]:
torch.chunk(x,2,dim=0) #拆分张量成等分块

(tensor([[[0., 1.],
          [2., 3.]]]),
 tensor([[[4., 5.],
          [6., 7.]]]))

In [33]:
torch.chunk(x,4,dim=0) #拆分张量成等分块

(tensor([[[0., 1.],
          [2., 3.]]]),
 tensor([[[4., 5.],
          [6., 7.]]]))

In [34]:
torch.chunk(x,2,dim=1) #拆分张量成等分块

(tensor([[[0., 1.]],
 
         [[4., 5.]]]),
 tensor([[[2., 3.]],
 
         [[6., 7.]]]))

In [35]:
torch.chunk(x,4,dim=1) #拆分张量成等分块

(tensor([[[0., 1.]],
 
         [[4., 5.]]]),
 tensor([[[2., 3.]],
 
         [[6., 7.]]]))

### 特殊张量

In [36]:
#全零元素张量
torch.zeros((2,2,2))

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [37]:
#全零元素张量匹配某一现有张量的形状
torch.zeros_like(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [38]:
#全一元素张量
torch.ones((2,2,2))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [39]:
#全一元素张量匹配某一现有张量的形状
torch.ones_like(x)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [40]:
#单位矩阵张量
torch.stack([torch.eye(3) for _ in range(3)])

tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])

In [41]:
#对角矩阵张量（增维并扩展）或者可用stack拼接方法
torch.diag(torch.arange(1, 4)).unsqueeze(0).expand(3, 3, 3)

tensor([[[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]],

        [[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]],

        [[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]]])

In [42]:
#随机数张量（取值0-1）
torch.rand(3,3)

tensor([[0.9187, 0.0303, 0.6352],
        [0.5970, 0.9627, 0.3929],
        [0.0242, 0.0626, 0.1790]])

In [43]:
#随机数并服从正态分布的张量（取值0-1）
torch.randn(3,3)

tensor([[-0.0440, -0.3654,  0.9280],
        [-0.1013,  0.6828, -1.8112],
        [-0.4377, -0.0968, -1.5783]])

In [44]:
#随机整数张量（取值为第一参数至第二参数之间，第三参数为形状）
torch.randint(3,6,(3,3))

tensor([[3, 5, 4],
        [5, 3, 4],
        [5, 4, 3]])

In [45]:
#等差数列张量（取值为第一参数至第二参数之间，第三参数为元素数量）
torch.linspace(0,1,5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [46]:
#初始化空张量
torch.empty(3,3)

tensor([[-1.0451e-28,  3.0969e-41, -1.0400e-28],
        [ 3.0969e-41,  1.1210e-43,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -4.1205e+32]])

In [47]:
#指定形状并填充为自定义第三参数的张量
torch.full([3,3],1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

### 张量转换成其他数据结构

In [48]:
#张量转换为numpy数组
x.numpy()

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

In [49]:
#张量转化为列表
x.tolist()

[[[0.0, 1.0], [2.0, 3.0]], [[4.0, 5.0], [6.0, 7.0]]]

### 张量克隆

In [50]:
y = x.clone()

In [51]:
display(x,y)

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [52]:
x[0,1,1]=0
display(x,y)

tensor([[[0., 1.],
         [2., 0.]],

        [[4., 5.],
         [6., 7.]]])

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

### 索引与切片

In [53]:
display(torch.arange(8))
display(torch.arange(8)[2:5]) #连续
display(torch.arange(8)[[2,4,6]]) #非连续
display(torch.arange(8)[2::2]) #起点：终点：步长（步长必须大于0）

tensor([0, 1, 2, 3, 4, 5, 6, 7])

tensor([2, 3, 4])

tensor([2, 4, 6])

tensor([2, 4, 6])

In [54]:
display(torch.arange(1,10).reshape(3,3))
display(torch.arange(1,10).reshape(3,3)[1:]) #连续行
display(torch.arange(1,10).reshape(3,3)[:,1:]) #连续列

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[4, 5, 6],
        [7, 8, 9]])

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [55]:
display(torch.arange(1,10).reshape(3,3))
display(torch.arange(1,10).reshape(3,3)[[0,2]]) #非连续行
display(torch.arange(1,10).reshape(3,3)[:,[0,2]]) #非连续列

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[1, 2, 3],
        [7, 8, 9]])

tensor([[1, 3],
        [4, 6],
        [7, 9]])

In [56]:
display(torch.arange(1,10).reshape(3,3))
display(torch.arange(1,10).reshape(3,3)[[0,2],[2,1]]) #指定交叉位置

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([3, 8])

In [57]:
display(torch.arange(1,10).reshape(3,3))
display(torch.arange(1,10).reshape(3,3)[::2]) #指定步长取行
display(torch.arange(1,10).reshape(3,3)[:,::2]) #指定步长取列

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[1, 2, 3],
        [7, 8, 9]])

tensor([[1, 3],
        [4, 6],
        [7, 9]])

In [58]:
display(torch.arange(1,19).reshape(2,3,3))
display(torch.arange(1,19).reshape(2,3,3)[0,1:3]) #第一个矩阵的连续行
display(torch.arange(1,19).reshape(2,3,3)[1,0:2]) #第二个矩阵的连续行
display(torch.arange(1,19).reshape(2,3,3)[0,:,0:2]) #第一个矩阵的连续列
display(torch.arange(1,19).reshape(2,3,3)[1,:,1:3]) #第二个矩阵的连续列

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([[4, 5, 6],
        [7, 8, 9]])

tensor([[10, 11, 12],
        [13, 14, 15]])

tensor([[1, 2],
        [4, 5],
        [7, 8]])

tensor([[11, 12],
        [14, 15],
        [17, 18]])

In [59]:
display(torch.arange(1,19).reshape(2,3,3))
display(torch.arange(1,19).reshape(2,3,3)[0,[0,2]]) #第一个矩阵的非连续行
display(torch.arange(1,19).reshape(2,3,3)[1,:,[0,2]]) #第二个矩阵的非连续列

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([[1, 2, 3],
        [7, 8, 9]])

tensor([[10, 12],
        [13, 15],
        [16, 18]])

In [60]:
display(torch.arange(1,19).reshape(2,3,3))
display(torch.arange(1,19).reshape(2,3,3)[0,[0,2],[2,1]]) #张量其中一个矩阵的交叉位置
display(torch.arange(1,19).reshape(2,3,3)[[0,1],
                                          [2,2],
                                          [1,0]]) #张量中多个矩阵的交叉位置（位置纵向对齐）

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([3, 8])

tensor([ 8, 16])

In [61]:
display(torch.arange(1,19).reshape(2,3,3))
display(torch.arange(1,19).reshape(2,3,3)[0,::2]) #第一个矩阵按照步长取行
display(torch.arange(1,19).reshape(2,3,3)[1,:,::2]) #第二个矩阵按照步长取列
display(torch.arange(1,19).reshape(2,3,3)[1,::2,::2]) #第二个矩阵按照步长取行和列

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([[1, 2, 3],
        [7, 8, 9]])

tensor([[10, 12],
        [13, 15],
        [16, 18]])

tensor([[10, 12],
        [16, 18]])

### 张量排序

In [62]:
x = torch.arange(1,19).reshape(2,3,3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [63]:
x.sort() #张量内的各矩阵内部列排序（从小到大的方向为从左往右）

torch.return_types.sort(
values=tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
indices=tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]))

In [64]:
x.sort(descending=True) #张量内的各矩阵内部列排序（从大到小的方向为从左往右）

torch.return_types.sort(
values=tensor([[[ 3,  2,  1],
         [ 6,  5,  4],
         [ 9,  8,  7]],

        [[12, 11, 10],
         [15, 14, 13],
         [18, 17, 16]]]),
indices=tensor([[[2, 1, 0],
         [2, 1, 0],
         [2, 1, 0]],

        [[2, 1, 0],
         [2, 1, 0],
         [2, 1, 0]]]))

In [65]:
x.sort(dim=0) #张量内以矩阵为单位排升序（从小到大的方向为从上往下）

torch.return_types.sort(
values=tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
indices=tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]))

In [66]:
x.sort(dim=0,descending=True) #张量内以矩阵为单位排降序（从大到小的方向为从上往下）

torch.return_types.sort(
values=tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]]),
indices=tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]))

In [67]:
x.sort(dim=1) #张量内各矩阵内部行排升序（从小到大的方向为从上往下）

torch.return_types.sort(
values=tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
indices=tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]]))

In [68]:
x.sort(dim=1,descending=True) #张量内各矩阵内部行排降序（从大到小的方向为从上往下）

torch.return_types.sort(
values=tensor([[[ 7,  8,  9],
         [ 4,  5,  6],
         [ 1,  2,  3]],

        [[16, 17, 18],
         [13, 14, 15],
         [10, 11, 12]]]),
indices=tensor([[[2, 2, 2],
         [1, 1, 1],
         [0, 0, 0]],

        [[2, 2, 2],
         [1, 1, 1],
         [0, 0, 0]]]))

In [69]:
x.sort(dim=2) #等价 x.sort()

torch.return_types.sort(
values=tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
indices=tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]))

In [70]:
x.sort(dim=2,descending=True) #等价 x.sort(descending=True)

torch.return_types.sort(
values=tensor([[[ 3,  2,  1],
         [ 6,  5,  4],
         [ 9,  8,  7]],

        [[12, 11, 10],
         [15, 14, 13],
         [18, 17, 16]]]),
indices=tensor([[[2, 1, 0],
         [2, 1, 0],
         [2, 1, 0]],

        [[2, 1, 0],
         [2, 1, 0],
         [2, 1, 0]]]))

### 广播机制

In [71]:
y = torch.arange(1,4).reshape(1,-1)
y = torch.cat([y,y],dim=0).reshape(2,1,-1)
display(x,y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([[[1, 2, 3]],

        [[1, 2, 3]]])

In [72]:
x+y #加减乘除

tensor([[[ 2,  4,  6],
         [ 5,  7,  9],
         [ 8, 10, 12]],

        [[11, 13, 15],
         [14, 16, 18],
         [17, 19, 21]]])

### 张量运算

In [73]:
torch.manual_seed(42)
torch.randn(3,3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [74]:
torch.manual_seed(42)
torch.abs(torch.randn(3,3)) #绝对值

tensor([[0.3367, 0.1288, 0.2345],
        [0.2303, 1.1229, 0.1863],
        [2.2082, 0.6380, 0.4617]])

In [75]:
torch.manual_seed(42)
torch.ceil(torch.randn(3,3)) #向上取整

tensor([[ 1.,  1.,  1.],
        [ 1., -1., -0.],
        [ 3., -0.,  1.]])

In [76]:
torch.manual_seed(42)
torch.floor(torch.randn(3,3)) #向下取整

tensor([[ 0.,  0.,  0.],
        [ 0., -2., -1.],
        [ 2., -1.,  0.]])

In [77]:
torch.manual_seed(42)
torch.round(torch.randn(3,3)) #四舍五入取整

tensor([[ 0.,  0.,  0.],
        [ 0., -1., -0.],
        [ 2., -1.,  0.]])

In [78]:
torch.manual_seed(42)
torch.neg(torch.randn(3,3)) #正负符号颠倒

tensor([[-0.3367, -0.1288, -0.2345],
        [-0.2303,  1.1229,  0.1863],
        [-2.2082,  0.6380, -0.4617]])

In [79]:
torch.manual_seed(42)
torch.pow(torch.randn(3,3),2) #n次幂

tensor([[0.1134, 0.0166, 0.0550],
        [0.0531, 1.2608, 0.0347],
        [4.8762, 0.4070, 0.2131]])

In [80]:
torch.manual_seed(42)
torch.sqrt(torch.pow(torch.randn(3,3),2)) #平方根

tensor([[0.3367, 0.1288, 0.2345],
        [0.2303, 1.1229, 0.1863],
        [2.2082, 0.6380, 0.4617]])

In [81]:
torch.manual_seed(42)
torch.log(torch.pow(torch.randn(3,3),2)) #自然常数为底的对数

tensor([[-2.1772, -4.0988, -2.9009],
        [-2.9365,  0.2318, -3.3605],
        [ 1.5844, -0.8988, -1.5459]])

In [82]:
torch.manual_seed(42)
torch.log1p(torch.pow(torch.randn(3,3),2)) #对张量所有元素+1后再计算自然常数为底的对数

tensor([[0.1074, 0.0165, 0.0535],
        [0.0517, 0.8157, 0.0341],
        [1.7709, 0.3415, 0.1932]])

In [83]:
torch.manual_seed(42)
torch.mean(torch.randn(3,3)) #均值

tensor(0.1837)

In [84]:
torch.manual_seed(42)
torch.median(torch.randn(3,3)) #中位数

tensor(0.2303)

In [85]:
torch.manual_seed(42)
torch.var(torch.randn(3,3)) #方差

tensor(0.8408)

In [86]:
torch.manual_seed(42)
torch.std(torch.randn(3,3)) #标准差

tensor(0.9169)

In [87]:
torch.manual_seed(42)
torch.var_mean(torch.randn(3,3)) #方差和均值

(tensor(0.8408), tensor(0.1837))

In [88]:
torch.manual_seed(42)
torch.std_mean(torch.randn(3,3)) #标准差和均值

(tensor(0.9169), tensor(0.1837))

In [89]:
torch.manual_seed(42)
torch.max(torch.randn(3,3)) #最大值

tensor(2.2082)

In [90]:
torch.manual_seed(42)
torch.min(torch.randn(3,3)) #最小值

tensor(-1.1229)

In [91]:
torch.manual_seed(42)
torch.argmax(torch.randn(3,3)) #最大值索引

tensor(6)

In [92]:
torch.manual_seed(42)
torch.argmin(torch.randn(3,3)) #最小值索引

tensor(4)

In [93]:
torch.manual_seed(42)
torch.sum(torch.randn(3,3)) #求和

tensor(1.6530)

In [94]:
torch.manual_seed(42)
torch.topk(torch.randn(3,3),2) #前n高的数值与索引

torch.return_types.topk(
values=tensor([[ 0.3367,  0.2345],
        [ 0.2303, -0.1863],
        [ 2.2082,  0.4617]]),
indices=tensor([[0, 2],
        [0, 2],
        [0, 2]]))

In [95]:
torch.manual_seed(42)
torch.dist(torch.randn(3,3),torch.randn(3,3),2) #计算张量间的距离（L2）

tensor(2.7878)

In [96]:
torch.manual_seed(42)
torch.dist(torch.randn(3,3),torch.randn(3,3),1) #计算张量间的距离（L1）

tensor(6.8658)

In [97]:
torch.manual_seed(42)
torch.randn(3,3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [98]:
torch.manual_seed(42)
torch.cumsum(torch.randn(3,3),dim=0) #按列累加和

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.5670, -0.9940,  0.0481],
        [ 2.7752, -1.6320,  0.5098]])

In [99]:
torch.manual_seed(42)
torch.cumsum(torch.randn(3,3),dim=1) #按行累加和

tensor([[ 0.3367,  0.4655,  0.7000],
        [ 0.2303, -0.8925, -1.0789],
        [ 2.2082,  1.5702,  2.0319]])

In [100]:
torch.manual_seed(42)
torch.randn(3,3)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [101]:
torch.manual_seed(42)
torch.diff(torch.randn(3,3),dim=0) #按行计算中间差（第二行与第一行的差，第三行与第二行的差）

tensor([[-0.1064, -1.2517, -0.4208],
        [ 1.9779,  0.4849,  0.6480]])

In [102]:
torch.manual_seed(42)
torch.diff(torch.randn(3,3),dim=1) #按列计算中间差（第二列与第一列的差，第三列与第二列的差）

tensor([[-0.2079,  0.1057],
        [-1.3532,  0.9365],
        [-2.8462,  1.0997]])

In [103]:
torch.manual_seed(42)
torch.count_nonzero(torch.randn(3,3)) #计算非零元素数量

tensor(9)

In [104]:
torch.manual_seed(42)
torch.sign(torch.randn(3,3)) #符号函数（负值为-1，正值为1，0为0）

tensor([[ 1.,  1.,  1.],
        [ 1., -1., -1.],
        [ 1., -1.,  1.]])

In [105]:
torch.manual_seed(42)
torch.randn(3,3)>0 #比较大于

tensor([[ True,  True,  True],
        [ True, False, False],
        [ True, False,  True]])

In [106]:
torch.manual_seed(42)
torch.randn(3,3)!=0 #比较不等于

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [107]:
torch.manual_seed(42)
torch.randn(3,3)==1 #比较等于

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

### 线性代数

In [108]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [109]:
x.mT #张量内各矩阵转置

tensor([[[ 1,  4,  7],
         [ 2,  5,  8],
         [ 3,  6,  9]],

        [[10, 13, 16],
         [11, 14, 17],
         [12, 15, 18]]])

In [110]:
torch.triu(x) #取矩阵上三角元素（下三角为0）

tensor([[[ 1,  2,  3],
         [ 0,  5,  6],
         [ 0,  0,  9]],

        [[10, 11, 12],
         [ 0, 14, 15],
         [ 0,  0, 18]]])

In [111]:
torch.tril(x) #取矩阵下三角元素（上三角为0）

tensor([[[ 1,  0,  0],
         [ 4,  5,  0],
         [ 7,  8,  9]],

        [[10,  0,  0],
         [13, 14,  0],
         [16, 17, 18]]])

In [112]:
display(torch.arange(4))
display(torch.dot(torch.arange(4),torch.arange(4))) #向量内积（逐元素相乘载相加）

tensor([0, 1, 2, 3])

tensor(14)

In [113]:
display(torch.arange(4).reshape(2,2))
display(torch.mm(torch.arange(4).reshape(2,2),torch.arange(4).reshape(2,2))) #矩阵内积

tensor([[0, 1],
        [2, 3]])

tensor([[ 2,  3],
        [ 6, 11]])

In [114]:
display(torch.arange(4).reshape(2,2))
display(torch.arange(2))
display(torch.mv(torch.arange(4).reshape(2,2),torch.arange(2))) #矩阵与向量内积

tensor([[0, 1],
        [2, 3]])

tensor([0, 1])

tensor([1, 3])

In [115]:
display(x)
display(torch.bmm(x,x)) #张量内矩阵批量内积

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]],

        [[435, 468, 501],
         [552, 594, 636],
         [669, 720, 771]]])

In [116]:
display(x[0])
display(torch.trace(x[0])) #矩阵的迹（对角线元素和）

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(15)

In [117]:
display(x[0])
display(torch.linalg.norm(x[0].float(),ord=1)) #矩阵L1范数

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(18.)

In [118]:
display(x[0])
display(torch.linalg.norm(x[0].float(),ord=2)) #矩阵L2范数

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(16.8481)

In [119]:
display(x[0])
display(torch.linalg.norm(x[0].float(),ord=np.inf)) #矩阵无穷范数

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(24.)

In [120]:
display(x[0])
display(torch.linalg.norm(x[0].float(),ord='fro')) #矩阵Frobenius范数

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(16.8819)

In [121]:
display(x[0].float())
display(torch.linalg.matrix_rank(x[0].float())) #矩阵的秩（线性无关的行/列最大数量）

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

tensor(2)

In [122]:
display(x[0].float())
display(torch.det(x[0].float())) #矩阵的行列式（行列式为0的矩阵不可逆）

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

tensor(0.)

In [123]:
torch.manual_seed(42)
display(torch.randn(3,3))
display(torch.det(torch.randn(3,3))) #矩阵的行列式（行列式为0的矩阵不可逆）

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

tensor(1.4866)

In [124]:
torch.manual_seed(42)
display(torch.randn(3,3))
display(torch.linalg.inv(torch.randn(3,3))) #矩阵的逆

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

tensor([[-0.0493,  0.4258,  0.5642],
        [-1.2477, -0.3746,  0.7824],
        [ 2.0764,  0.1069, -0.7034]])

In [125]:
display(x[0].float())
torch.linalg.eig(x[0].float()) #计算矩阵特征值与特征向量

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

torch.return_types.linalg_eig(
eigenvalues=tensor([ 1.6117e+01+0.j, -1.1168e+00+0.j, -1.5613e-07+0.j]),
eigenvectors=tensor([[-0.2320+0.j, -0.7858+0.j,  0.4082+0.j],
        [-0.5253+0.j, -0.0868+0.j, -0.8165+0.j],
        [-0.8187+0.j,  0.6123+0.j,  0.4082+0.j]]))

In [126]:
display(x[0].float())
eigvalue, eigvector = torch.linalg.eig(x[0].float())
torch.mm(torch.mm(eigvector, torch.diag(eigvalue)) ,torch.linalg.inv(eigvector)) #基于特征值与特征向量还原矩阵

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

tensor([[1.0000+0.j, 2.0000+0.j, 3.0000+0.j],
        [4.0000+0.j, 5.0000+0.j, 6.0000+0.j],
        [7.0000+0.j, 8.0000+0.j, 9.0000+0.j]])

In [127]:
display(x[0].float())
torch.linalg.svd(x[0].float()) #矩阵奇异值分解

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

torch.return_types.linalg_svd(
U=tensor([[-0.2148,  0.8872,  0.4082],
        [-0.5206,  0.2496, -0.8165],
        [-0.8263, -0.3879,  0.4082]]),
S=tensor([1.6848e+01, 1.0684e+00, 2.3721e-07]),
Vh=tensor([[-0.4797, -0.5724, -0.6651],
        [-0.7767, -0.0757,  0.6253],
        [-0.4082,  0.8165, -0.4082]]))

In [128]:
display(x[0].float())
u,s,vt = torch.linalg.svd(x[0].float())
display(torch.mm(torch.mm(u, torch.diag(s)),vt)) #矩阵奇异值分解再还原

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.0000]])

In [129]:
torch.linalg.lu(x[0].float()) #矩阵LU分解（矩阵分解为下三角矩阵对角线元素为1，上三角矩阵）(LU仅适用于方矩阵)

torch.return_types.linalg_lu(
P=tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
L=tensor([[1.0000, 0.0000, 0.0000],
        [0.1429, 1.0000, 0.0000],
        [0.5714, 0.5000, 1.0000]]),
U=tensor([[7.0000, 8.0000, 9.0000],
        [0.0000, 0.8571, 1.7143],
        [0.0000, 0.0000, 0.0000]]))

In [130]:
torch.linalg.qr(x[0].float()) #矩阵QR分解（矩阵分解为正交矩阵和上三角矩阵）

torch.return_types.linalg_qr(
Q=tensor([[-0.1231,  0.9045,  0.4082],
        [-0.4924,  0.3015, -0.8165],
        [-0.8616, -0.3015,  0.4082]]),
R=tensor([[-8.1240e+00, -9.6011e+00, -1.1078e+01],
        [ 0.0000e+00,  9.0453e-01,  1.8091e+00],
        [ 0.0000e+00,  0.0000e+00, -4.7684e-07]]))

### 自动求解最小二乘

In [131]:
#用最小二乘法手动求解系数
x = x.float()
g = x[0,:,:2]
h = x[0,:,-1:]
display(a,b)
display(torch.mm(torch.linalg.inv(torch.mm(g.mT,g)), (g.mT @ h)))
y = -1 * g[:,0] + 2 * g[:,1] #函数为 y=-1x_1+2x_2
display(y)

tensor([[[0., 1.]],

        [[4., 5.]]])

tensor([[[2., 0.]],

        [[6., 7.]]])

tensor([[-1.],
        [ 2.]])

tensor([3., 6., 9.])

In [132]:
w = torch.linalg.lstsq(g, h).solution #用最小二乘法自动求解系数
w

tensor([[-1.],
        [ 2.]])

### 自动微分

In [133]:
x = torch.arange(1.0, 5) #设定输入数据x
y = torch.arange(2.0,9,2) #设定真实数据y
display(x,y)

tensor([1., 2., 3., 4.])

tensor([2., 4., 6., 8.])

In [134]:
w = torch.tensor(1.0, requires_grad=True) #设置初始权重w（启用梯度）
w       #只对需要优化的参数开启梯度追踪，其他参数无需开启（损失函数和中间激活函数计算将自动继承梯度追踪）

tensor(1., requires_grad=True)

In [135]:
yhat = w*x
yhat

tensor([1., 2., 3., 4.], grad_fn=<MulBackward0>)

In [136]:
loss = ((yhat-y)**2).mean()
loss

tensor(7.5000, grad_fn=<MeanBackward0>)

In [137]:
loss.backward()

In [138]:
w.grad

tensor(-15.)

### 自动微分的梯度下降实现

In [139]:
def gradient(x,y,epoch,lr):
    #随机初始化权重和截距（创建与1行n列的权重向量，一个标量）
    w = torch.randn((1,x.shape[1]), dtype=torch.float32, requires_grad=True)
    b = torch.randn(1, dtype=torch.float32, requires_grad=True)

    for epoch in range(epoch):
        loss = torch.mean((torch.mm(x,w.T)+b-y)**2) #计算MSE损失
        loss.backward()                             #损失求梯度（反向传播）
        
        with torch.no_grad():                       #声明以下操作pytorch无需追踪梯度（阻止计算图追踪）
            w -= lr * w.grad                        #更新权重
            b -= lr * b.grad                        #更新截距

        w.grad.zero_()                              #梯度重置为0
        b.grad.zero_()                              #梯度重置为0
        
        if epoch %50 == 0:
            print(f'迭代{epoch}次: w:{w}; loss:{loss}')

    return w,b,loss

In [140]:
display(g,h)

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

tensor([[3.],
        [6.],
        [9.]])

In [141]:
# g = (g-torch.mean(g))/torch.std(g) #可选标准化来加速收敛

In [142]:
w, b, loss = gradient(x=g, y=h, epoch=1500, lr=0.01)
display(w,b,loss)

迭代0次: w:tensor([[0.4533, 0.6977]], requires_grad=True); loss:169.41688537597656
迭代50次: w:tensor([[0.3917, 0.5861]], requires_grad=True); loss:0.0038511145394295454
迭代100次: w:tensor([[0.4071, 0.5770]], requires_grad=True); loss:0.0019645781721919775
迭代150次: w:tensor([[0.4182, 0.5705]], requires_grad=True); loss:0.001002187724225223


迭代200次: w:tensor([[0.4261, 0.5658]], requires_grad=True); loss:0.0005112504004500806
迭代250次: w:tensor([[0.4317, 0.5625]], requires_grad=True); loss:0.00026080591487698257
迭代300次: w:tensor([[0.4357, 0.5601]], requires_grad=True); loss:0.00013304180174600333
迭代350次: w:tensor([[0.4386, 0.5585]], requires_grad=True); loss:6.786142330383882e-05
迭代400次: w:tensor([[0.4406, 0.5572]], requires_grad=True); loss:3.462149470578879e-05
迭代450次: w:tensor([[0.4421, 0.5564]], requires_grad=True); loss:1.766111199685838e-05
迭代500次: w:tensor([[0.4432, 0.5558]], requires_grad=True); loss:9.010221219796222e-06
迭代550次: w:tensor([[0.4439, 0.5553]], requires_grad=True); loss:4.59590410173405e-06
迭代600次: w:tensor([[0.4444, 0.5550]], requires_grad=True); loss:2.3454383608623175e-06
迭代650次: w:tensor([[0.4448, 0.5548]], requires_grad=True); loss:1.1963314818785875e-06
迭代700次: w:tensor([[0.4451, 0.5546]], requires_grad=True); loss:6.100694349697733e-07
迭代750次: w:tensor([[0.4453, 0.5545]], requires_grad=True); loss

tensor([[0.4458, 0.5542]], requires_grad=True)

tensor([1.4458], requires_grad=True)

tensor(2.4026e-11, grad_fn=<MeanBackward0>)

In [143]:
w[0,0]*g[:,0]+w[0,1]*g[:,1]+b

tensor([3.0000, 6.0000, 9.0000], grad_fn=<AddBackward0>)

In [144]:
w.grad #调用自动微分的梯度值

tensor([[0., 0.]])

In [145]:
b.grad

tensor([0.])

In [146]:
w.is_leaf #检查该变量是否为叶子节点（即原始输入变量）

True

In [147]:
b.is_leaf

True

In [148]:
loss.is_leaf #检查该变量是否为叶子节点（即原始输入变量）

False

In [149]:
w.data #查看epoch迭代完的梯度值（即权重w的值）

tensor([[0.4458, 0.5542]])

In [150]:
b.data #查看epoch迭代完的梯度值（即截距b的值）

tensor([1.4458])